max_lr: 0.0001 #0.01
weight_decay: 0.0001
momentum: 0.9
max_epochs: 100
batch_size: 8

in_channels: 1
num_classes: 3
use_pretrained_weights: true

test_model: false
checkpoint_path: #./checkpoints/tdt17/vggunet_multi_mid_01/best_model.ckpt #used for when test model = true
early_stopping_patience: 3
num_workers: 0
check_val_every_n_epoch: 3
devices: auto
enable_progress_bar: True
device: "cuda"

wandb_project: tdt17
wandb_experiment_name: vggunet_multi_mid_02 #attentionunet_10

train_split_ratio: 0.8
val_split_ratio: 0.25
data_root: ./data
checkpoint_folder: ./checkpoints/