max_lr: 0.01
weight_decay: 0.0001
momentum: 0.9
max_epochs: 100
batch_size: 8

in_channels: 1
num_classes: 1
use_pretrained_weights: true

test_model: false
checkpoint_path: #./checkpoints/ASOCA/UNet_final/best_model.ckpt #used for when test model = true
early_stopping_patience: 10
num_workers: 0
check_val_every_n_epoch: 3
devices: auto
enable_progress_bar: True
device: "cuda"

wandb_project: tdt17
wandb_experiment_name: vggunet_test

train_split_ratio: 0.7
val_split_ratio: 0.15
data_root: ./data
checkpoint_folder: ./checkpoints/